name: SpawnerAlerts
version: '${project.version}'
main: org.me.pyke.spawneralerts.SpawnerAlerts
api-version: '1.20'
author: 666pyke

permissions:
  spawneralerts.notify:
    description: Allows the player to receive alerts when a spawner is broken.
    default: op

commands:
  spawneralerts:
    description: Main command for managing SpawnerAlerts.
    usage: /spawneralerts reload